language: node_js
node_js: 8

# local paths in PATH break `find -execdir`
before_script:
  - PATH=${PATH//:\.\/node_modules\/\.bin/}

install:
  - npm install

script:
  - npx bower install
  - npm -s test

# after_success:
# - >-
#   test $TRAVIS_TAG &&
#   echo $GITHUB_TOKEN | pulp login &&
#   echo y | pulp publish --no-push
